### ISSUE TITLE
slack invite not sending invite

### ISSUE THREAD

**Issue by cccsss01** [deployKF/website#109]
Trying to a get slack invite but nothing happening

**Comment by thesuperzapper** [comment]
@cccsss01 make sure you typed your email exactly correctly.

Once you check that, if it's still not working, can you share a redacted version of your email so I can see if it's in the log?
E.g. `myemaXXXXX@gmail.com`

There are a crazy number of people joining at the moment, so the bot might also be having trouble.

**Comment by thesuperzapper** [comment]
@cccsss01 also, I have set up another invite bot, can you see if this one works for you?

https://communityinviter.com/apps/kubeflow/slack

**Comment by cccsss01** [comment]
error already in team

**Comment by cccsss01** [comment]
So this is the standard kubeflow slack?  i thought deployKF had it's own slack

**Comment by thesuperzapper** [comment]
@cccsss01 yes, we are using the Kubeflow Slack for now. 

We will probably create our own Discord or Slack once we add non-Kubeflow tools (and grow beyond Kubelfow).

Just so we are clear, you are already in the Kubeflow slack, if so, join the `#deploykf` channel!
